spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-role-service
          uri: lb://user-role-service
          predicates:
            - Path=/api/users/**,/api/roles/**
          filters:
            - name: JwtAuthFilter
              args:
                roles:
                    - admin
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
        - id: project
          uri: lb://project
          predicates:
            - Path=/api/offers/**
          filters:
            - name : JwtAuthFilter
              args:
                roles:
                    - ADMIN

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

jwt:
  secret: secret
  expiration: 86400000